clubbiz/config/routes.rb
Clubbiz::Application.routes.draw do
 
  get "admins/dashboard"
  get "admins/pending_club/:id" => "admins#pending_club", as: "admins_pending_club"

  get 'club_admins/eventdisplay' => "club_admins#eventdisplay", as: "clubadmin_eventdisplay"
  get "club_admins/dashboard/:id" => "club_admins#dashboard", as: "dashboard"
  get "club_admins/events/:id" => "club_admins#events", as: "clubadmin_events"
  get "club_admins/settings/:id" => "club_admins#settings", as: "clubadmin_settings"
  
  get "permission_denied" => "pages#permission_denied", as: "permission_denied"
  get "about" => "pages#help", as: "help"
  get "terms" => "pages#terms", as: "terms"
  get "privacy" => "pages#privacy", as: "privacy"
  get "about" => "pages#about", as: "about"
  get "search" => "pages#search", as: "search"

  resources :shared_events, only: [:edit, :create, :update, :destroy]

  resources :event_comments, only: [:edit, :create, :update, :destroy]
  get "event_comments/new/:id" => "event_comments#new", as: "new_event_comment"

  resources :club_comments, only: [:edit, :create, :update, :destroy]
  get "club_comments/new/:id" => "club_comments#new", as: "new_club_comment"

  resources :memberships, only: [:index, :edit, :create, :update, :destroy]
  get "memberships/new/:id" => "memberships#new", as: "new_membership"
  
  resources :tickets

  resources :ticket_allocations, except: [:new]
  get "ticket_allocations/new/:id" => "ticket_allocations#new", as: "new_ticket_allocation"

  resources :events, except: [:new]
  get "events/new/:id" => "events#new", as: "new_event"

  devise_for :users
  get "users/:id" => 'users#show', as: 'user'
  resources :clubs

  root to: "pages#home"
  

end

clubbiz/app/controllers/club_admins_controller.rb
class ClubAdminsController < ApplicationController

	before_action :set_club, only: [:dashboard, :events, :settings]

  def dashboard
  	@display_events = @club.events.order("start_datetime DESC")
  end

  def events
  	@shared_event_requests = @club.shared_events.where(role: "pending")
  end

  def settings
  	@membership = Membership.new
  end

  def eventdisplay
  	@event = Event.find(params[:event_id])
  end

  private
  	def set_club
  		@club = Club.find(params[:id])
  	end
end

clubbiz/app/helpers/club_admins_helper.rb
module ClubAdminsHelper
	  def resource_name
	    :user
	  end
	 
	  def resource
	    @resource ||= User.new
	  end
	 
	  def devise_mapping
	    @devise_mapping ||= Devise.mappings[:user]
	  end
end

clubbiz/app/views/club_admins/_eventdisplay.html.erb
<h4>
	<em>Event Information</em>
	<%= link_to "Edit", edit_event_path(event) ,class: "btn btn-default btn-xs pull-right" %>
	<%= link_to "View", event_path(event) ,class: "btn btn-default btn-xs pull-right" %>
</h4>
<table class="table table-striped">
	<tr>
		<td><strong>Event</strong></td>
		<td><%= event.event_name %></td>
	</tr>
	<tr>
		<td><strong>Host Club</strong><str</td>
		<td><%= event.host_club.club_name %></td>
	</tr>
	<tr>
		<td><strong>venue</strong><str</td>
		<td><%= event.venue %></td>
	</tr>
	<tr>
		<td><strong>Start Time</strong><str</td>
		<td><%= event.start_datetime %><strong></strong></td>
	</tr>
	<tr>
		<td><strong>End Time</strong><str</td>
		<td><%= event.end_datetime %></td>
	</tr>
	<tr>
		<td><strong>Status</strong><str</td>
		<td><%= event.status %></td>
	</tr>
</table>
<h4><em>Ticket</em></h4>
<table class="table table-striped">
	<tr>
		<th>Ticket Type</th>
		<th>Price</th>
		<th>Start Sale</th>
		<th>End Sale</th>
		<th>Sale Status</th>
		<th>Remaining</th>
	</tr>
	<% event.tickets.each do |ticket| %>
	<tr>
		<td><%= ticket.ticket_type %></td>
		<td><%= ticket.ticket_cost %></td>
		<td><%= ticket.start_sale_datetime %></td>
		<td><%= ticket.end_sale_datetime %></td>
		<td><%= ticket.get_sale_status %></td>
		<td><%= ticket.no_reserved %> / <%= ticket.quantity %></td>
	</tr>
	<% end %>
</table>

clubbiz/app/views/club_admins/_shared_event_request.html.erb
<div class="col-md-12 cb-ticket-list-element">	
	<div class="col-md-6">
		<strong>Host Club: </strong><%= shared_event_request.event.host_club.club_name %><br>
		<strong>Event Name: </strong><%= shared_event_request.event.event_name %>
	</div>
	<div class="col-md-6">
		<%= form_for shared_event_request do |f| %>
			<%= f.hidden_field :role, :value => "shared" %>
			<%= f.submit "Accept" %>
		<% end %>
		<%= form_for shared_event_request do |f| %>
			<%= f.hidden_field :role, :value => "rejected" %>
			<%= f.submit "Decline" %>
		<% end %>
	</div>
</div>

clubbiz/app/views/club_admins/dashboard.html.erb
<div class="row" id="main-content">
  <div class="col-md-5 pull-right">
    <%= render "shared/search_all" %>
  </div>

  <div class="col-md-5">
    <h2 style="margin-top:0"><%= @club.club_name %> Moderator Page</h2> 
  </div>

  <div class="col-md-12">
		<div class="col-sm-4"><%= link_to "Dashborad", dashboard_path(@club), class: "btn btn-default btn-block" %></div>
		<div class="col-sm-4"><%= link_to "Shared Events", clubadmin_events_path(@club), class: "btn btn-default btn-block" %></div>
		<div class="col-sm-4"><%= link_to "Settings", clubadmin_settings_path(@club), class: "btn btn-default btn-block" %></div>		
	</div>

	<div class="col-md-12">
		<div class="col-md-7">
			<%= render partial: "events/listall", object: @display_events, as: :events %>
		</div>
		<div class="col-md-5">

		</div>
	</div>
</div>

clubbiz/app/views/club_admins/eventdisplay.js.erb
$("#cb-eventdisplay-container").html("<%= escape_javascript(render partial: 'club_admins/eventdisplay', object: @event, as: :event) %>");

clubbiz/app/views/club_admins/events.html.erb
<div class="row" id="main-content">
  <div class="col-md-5 pull-right">
    <%= render "shared/search_all" %>
  </div>

  <div class="col-md-5">
    <h2 style="margin-top:0">Club Moderator Page</h2> 
  </div>

  <div class="col-md-12">
		<div class="col-sm-4"><%= link_to "Dashborad", dashboard_path(@club), class: "btn btn-default btn-block" %></div>
		<div class="col-sm-4"><%= link_to "Shared Events", clubadmin_events_path(@club), class: "btn btn-default btn-block" %></div>
		<div class="col-sm-4"><%= link_to "Settings", clubadmin_settings_path(@club), class: "btn btn-default btn-block" %></div>		
	</div>

	<div class="col-md-12">
		<div class="col-md-8">
			<h4><em>Event Deatils</em></h4>
			<script type="text/javascript">
				$(document).ready(function() {
				    $('#event_select').change(function() {
				      $.ajax({
				        url: "<%= clubadmin_eventdisplay_path %>",
				        data: {
				          event_id : $('#event_select').val()
				        },
				        dataType: "script"
				      });
				    });
				  });
			</script>

			<%= collection_select(nil, :event_id,  @club.events,  :id, :event_name, {:prompt   => "Select an Event"}, {:id => 'event_select', class: "form-control"}) %>
			<div class="col-md-12" id="cb-eventdisplay-container">
				<div class="alert alert-info">Select an event from the dropdown above to see event and ticket summary</div>
			</div>
		</div>
		<dic class="col-md-4">
			<h4><em>Shared Event Requests</em></h4>
			<% if !@shared_event_requests.empty? %>
				<%= render partial: "club_admins/shared_event_request", collection: @shared_event_requests, as: :shared_event_request %>
			<% else %>
				<center><strong>You have now shared event requests</strong></center>
			<% end %>
		</div>
	</div>
</div>

clubbiz/app/views/club_admins/settings.html.erb
<div class="row" id="main-content">
  <div class="col-md-5 pull-right">
    <%= render "shared/search_all" %>
  </div>

  <div class="col-md-5">
    <h2 style="margin-top:0">Club Moderator Page</h2> 
  </div>

  <div class="col-md-12">
		<div class="col-sm-4"><%= link_to "Dashborad", dashboard_path(@club), class: "btn btn-default btn-block" %></div>
		<div class="col-sm-4"><%= link_to "Shared Events", clubadmin_events_path(@club), class: "btn btn-default btn-block" %></div>
		<div class="col-sm-4"><%= link_to "Settings", clubadmin_settings_path(@club), class: "btn btn-default btn-block" %></div>		
	</div>

	<div class="col-md-12">
		<%= render 'clubs/edit_form' %>
	</div>
</div>