clubbiz/config/routes.rb
Clubbiz::Application.routes.draw do
 
  get "admins/dashboard"
  get "admins/pending_club/:id" => "admins#pending_club", as: "admins_pending_club"

  get 'club_admins/eventdisplay' => "club_admins#eventdisplay", as: "clubadmin_eventdisplay"
  get "club_admins/dashboard/:id" => "club_admins#dashboard", as: "dashboard"
  get "club_admins/events/:id" => "club_admins#events", as: "clubadmin_events"
  get "club_admins/settings/:id" => "club_admins#settings", as: "clubadmin_settings"
  
  get "permission_denied" => "pages#permission_denied", as: "permission_denied"
  get "about" => "pages#help", as: "help"
  get "terms" => "pages#terms", as: "terms"
  get "privacy" => "pages#privacy", as: "privacy"
  get "about" => "pages#about", as: "about"
  get "search" => "pages#search", as: "search"

  resources :shared_events, only: [:edit, :create, :update, :destroy]

  resources :event_comments, only: [:edit, :create, :update, :destroy]
  get "event_comments/new/:id" => "event_comments#new", as: "new_event_comment"

  resources :club_comments, only: [:edit, :create, :update, :destroy]
  get "club_comments/new/:id" => "club_comments#new", as: "new_club_comment"

  resources :memberships, only: [:index, :edit, :create, :update, :destroy]
  get "memberships/new/:id" => "memberships#new", as: "new_membership"
  
  resources :tickets

  resources :ticket_allocations, except: [:new]
  get "ticket_allocations/new/:id" => "ticket_allocations#new", as: "new_ticket_allocation"

  resources :events, except: [:new]
  get "events/new/:id" => "events#new", as: "new_event"

  devise_for :users
  get "users/:id" => 'users#show', as: 'user'
  resources :clubs

  root to: "pages#home"
  

end

clubbiz/app/models/event.rb
class Event < ActiveRecord::Base
	
#	belongs_to :club

	has_many :shared_events, dependent: :destroy
	has_many :clubs, :through => :shared_events

	has_many :event_comments

	has_many :tickets, dependent: :destroy
	
	accepts_nested_attributes_for :shared_events

	def self.search(query)
		where("event_name like ?", "%#{query}%")
	end

	def self.all_active
		where(status: "active")
	end

	def host_club
		Club.find(self.shared_events.where(role: "owner").first.club_id)
	end

	def associate_clubs
		self.shared_events.where(role: "shared")
	end

	def viewable_associate_clubs(user)
		if self.can_be_modified_by?(user)
			self.shared_events.where(role: "owner")
		else
			self.associate_clubs
		end
	end

	# handling .R.. permissions
	def can_be_viewed_by?(user)
		self.host_club.active_members.map(&:user_id).include? user.id
	end

	# handing C.UD permissions
	def can_be_modified_by?(user)
		self.host_club.moderators.map(&:user_id).include? user.id
	end

end

clubbiz/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_club, only: [:new]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @club = @event.host_club
    @club_events = @club.events.where(status: "active")
    @fevent = @club.get_next_event
    @event_comment = EventComment.new
    @new_ticket = Ticket.new
    @shared_event = SharedEvent.new
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.shared_events.build(role: "owner")
  end

  # GET /events/1/edit
  def edit
    @club = Club.find(@event.shared_events.where(role: "owner").first.club_id)
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy    
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_name, :event_description, :start_datetime, :end_datetime, :external_url, :venue, :access, :featured, :ticketed, :status, shared_events_attributes: [:id, :club_id, :role])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

end

clubbiz/app/helpers/events_helper.rb
module EventsHelper
end

clubbiz/app/views/events/_comment_display.html.erb
<table class="table table-striped">
	<tr>
		<th>comment_title</th>
		<th>comment_body</th>
		<th>posted</th>
		<th>poster</th>
	</tr>
	<% if !@event.event_comments.where(comment_type: "Comment").empty? %>
		<% @event.event_comments.where(comment_type: "Comment").each do |event_comment| %>
		<tr>
			<td><%= event_comment.comment_title %></td>
			<td><%= event_comment.comment_body %></td>
			<td><%= distance_of_time_in_words_to_now(event_comment.created_at) %></td>
			<td><%= event_comment.user.displayname %></td>
		</tr>	
		<% end %>
	<% else %>
		<tr>
			<td colspan="4"><center>There are no comments, must be doing somethin' right</center></td>
		</tr>
	<% end %>
		<tr>
			<td colspan="4"><center><%= link_to "Add new comment", new_event_comment_path(@event) %></center></td>
		</tr>
</table>

clubbiz/app/views/events/_event.html.erb
<% club = event.host_club %>
<div class="media cb-event-list-element">
  <a class="pull-left" href="#">
    <img class="media-object" src="http://placehold.it/80x80">
  </a>
  <div class="media-body">
    <strong><%= link_to event.event_name, event_path(event) %></strong>
    <div class="dropdown pull-right">
      <a data-toggle="dropdown" href="#" style="color: #000"><b class="caret"></b> </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li><a href="">View</a></li>
        <li><a href="">Tickets</a></li>
      </ul>
    </div>
    <br>
    <small><%= event.start_datetime %><br><em>MUST ADD LOC TO EVENT DB</em><br><%= event.event_description %></small>
  </div>
</div>

clubbiz/app/views/events/_featured_event.html.erb
<div class="row well">
	<div id="featured_events">
	  <div class="">
	    <img class="pull-right" src="http://placehold.it/250x150"/>
	    <p>
	      <strong>Next Event</strong><br>
	      <small>
	      	<strong>Club: </strong><%= event.host_club.club_name %><br>
	      	<strong>Event: </strong><%= event.event_name %><br>
	      	<%= event.start_datetime %><br>
	      	<%= event.venue %><br>
	      </small>
	      <%= event.event_description %>
	      <%= link_to "View Event", event_path(event), class: "btn btn-default btn-xs" %>
	    </p>
	  </div>
	</div>
</div>

clubbiz/app/views/events/_form.html.erb
    
<div class="col-md-7">
  <%= form_for(@event) do |f| %>
    <h4>Host Club: <%= @club.club_name %></h4>
    <div class="form-group">
      <%= f.label :event_name %>
      <%= f.text_field :event_name, class: "form-control", placeholder:"Event Name" %>
    </div>
    <div class="form-group">
      <%= f.label :event_description %>
      <%= f.text_field :event_description, class: "form-control", placeholder: "Description" %>
    </div>
    <div class="form-group">
      <%= f.label :venue %>
      <%= f.text_field :venue, class: "form-control", placeholder:"Venue Address, Location on Campus" %>
    </div>
    <div class="form-group">
      <%= f.label :start_datetime %>
      <%= f.datetime_select :start_datetime, class: "form-control", placeholder:"Click to select" %>
      <div id="dtBox"></div>
    </div>
    <div class="form-group">
      <%= f.label :end_datetime %>
      <%= f.datetime_select :end_datetime, class:"form-control", placeholder:"Click to select" %>
    </div>
    
    <h4>Event Settings</h4>
    <table class="table">
      <tr>
        <td>Event Opacity</td>
        <td>
          <div class="radio-inline">
            <label>
              <input type="radio" name="event[access]" id="event_access_0" value="public" checked>
              Public
            </label>
          </div><div class="radio-inline">
            <label>
              <input type="radio" name="event[access]" id="event_access_1" value="private">
              Private
            </label>
          </div>
      </td>
      </tr>
      <tr>
        <td>Ticketing</td>
        <td>
          <div class="radio-inline">
            <label>
              <input type="radio" name="event[ticketed]" id="event_ticketed_0" value="false" checked>
              Free
            </label>
          </div><div class="radio-inline">
            <label>
              <input type="radio" name="event[ticketed]" id="event_ticketed_1" value="true">
              Ticketed
            </label>
          </div>
        </td>
      </tr>
    </table>

    <%= f.fields_for :shared_events do |se| %>
      <%= se.hidden_field :club_id, :value => @club.id %>
      <%= se.hidden_field :role, :value => "owner" %>
    <% end %>
    <%= f.hidden_field :featured, :value => false %>
    <%= f.hidden_field :status, :value => "pending" %>
  <div class="form-group">
    <%= f.submit %>
  </div>
  <% end %>
</div>   


<div class="col-md-5">
  <h4>So, how does this whole event thing work?</h4>
  <p>
    Signing up for ClubBiz allows for your club to manage its events and tickets with ease. Take the worry out of promoting your event and informing your members of your latest event, and just get on with it.
  </p>
  <p>
    With all of your current members, and hundreds of potential new members already using our site, you'd be stupid not to continue. Fill in your details and click 'Next'.
  </p>
</div>

clubbiz/app/views/events/_listall.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Host Club</th>
      <th>Event name</th>
      <th>Role</th>
      <th>Start datetime</th>
      <th>Status</th>
      <th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% events.each do |event| %>
      <tr>
        <td><%= link_to event.host_club.club_name, event.host_club %></td>
        <td><%= link_to event.event_name, event %></td>
        <td><%= event.shared_events.where(:club_id => @club.id).first.role %></td>
        <td><%= event.start_datetime.strftime('%H:%M, %a %b %d %Y') %></td>
        <td><% if event.start_datetime < Time.now %>finished<% else %><%= event.status %><% end %></td>
        <td>
          <% if event.host_club == @club %>
            <% if event.start_datetime < Time.now %>
              <a href="" class="btn btn-default btn-xs">Report</a>
            <% else %>
              <%= link_to "edit", edit_event_path(event), class: "btn btn-default btn-xs" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

clubbiz/app/views/events/edit.html.erb
<div class="row" id="main-content">
  
  <div class="col-md-7">
      <h2 style="margin-top:0">Edit your Event</h2>
  </div>
    
  <div class="col-md-12"></div>

  <%= render 'form' %>

</div>

clubbiz/app/views/events/index.html.erb
<h1>Listing all events</h1>

<%= render "listall" %>

clubbiz/app/views/events/new.html.erb
<div class="row" id="main-content">
  
  <div class="col-md-7">
      <h2 style="margin-top:0">Register your Event</h2>
  </div>
    
  <div class="col-md-12"></div>

  <%= render 'form' %>

</div>

clubbiz/app/views/events/show.html.erb
<div class="row" id="main-content">
  <div class="col-md-4 pull-right col-md-pull-2 cb-search-element">
    <%= render "shared/search_all" %>
  </div>



  <div class="col-sm-6 col-md-6">

    <div class="row">
      <div class="col-md-10">
        
        <div class="row">
          
          <img src="http://placehold.it/100x100" class = "pull-left" width="65px">
          <h2> <%= link_to @club.club_name, club_path(@club) %></h2>

          <ul class="nav nav-tabs pull-right">
            <li class="active"><a href="#details" data-toggle="tab">Event Details</a></li>
            <li><a href="#discussions" data-toggle="tab">Discussions</a></li>
          </ul>

        </div> 

        <div class="tab-content row">
          
          <div class="tab-pane fade in active" id="details">
            
            <div class="col-md-8">
              <h2><%= @event.event_name %></h2>
              <small>
                <%= @event.start_datetime %><br>
                <em>Ad LOC to DB</em><br>
                <%= @event.event_description %>
              </small>
            </div>

            <div class="col-md-4">
              <img src="http://placehold.it/170x170" width="100%">
            </div>

            <% if signed_in? && @event.can_be_modified_by?(current_user) && @event.status == "pending" %>
              <div class="col-md-12 alert alert-warning text-center">
                Your event is currently inactive, 
                <%= form_for @event do |f| %>
                  <%= f.hidden_field :status, :value => "active" %>
                  <%= f.submit "Go Live", {:class => "btn btn-warning btn-xs", data: { confirm: 'Are you sure?' }} %>
                <% end %>
              </div>
            <% end %>

          </div>

          <div class="tab-pane fade" id="discussions">
            <div id="cb-club-comment-wrapper">
                        
              <%= render @event.event_comments %>
              
            </div>
            <% if signed_in? %>
              <%= render partial: "event_comments/form", object: {:event_comment => @event_comment, :current_user => current_user, :event => @event} %>
            <% end %>
          </div>

        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-10 ">
        <div class ="col-md-12">
          <% if @event.ticketed %>
            <h4>Tickets</h4>
            <% if @event.tickets.current_sale.empty? %>
              <center>This event has not tickets on sale yet,<br>please check back soon</center>
            <% else %>
              <%= render @event.tickets.current_sale %>
            <% end %>
            <% if signed_in? && @event.can_be_modified_by?(current_user) %>
              <%= form_for @new_ticket do |f| %>
                <%= f.hidden_field :event_id, :value => @event.id %>
                <div class="form-group col-md-6">
                  <%= f.label :ticket_type %>
                  <%= f.text_field :ticket_type, class: "form-control", placeholder: "Ticket type, eg genearl admission" %>
                </div>
                <div class="form-group col-md-4">
                  <%= f.label :ticket_cost %>
                  <%= f.text_field :ticket_cost, class: "form-control", placeholder: "Ticket type, eg genearl admission" %>
                </div>
                <div class="form-group col-md-2">
                  <%= f.label :quantity %>
                  <%= f.text_field :quantity, class: "form-control", placeholder: "Ticket type, eg genearl admission" %>
                </div>
                <div class="form-group col-md-6">
                  <%= f.label :start_sale_date %>
                  <%= f.text_field :start_sale_datetime, class: "form-control", placeholder: "Click to update" %>
                </div>
                <div class="form-group col-md-6">
                  <%= f.label :end_sale_date %>
                  <%= f.text_field :end_sale_datetime, class: "form-control", placeholder: "Click to udpate" %>
                </div>
                <%= f.submit "add ticket" %>
              <% end %>
            <% end %>
          <% else %>  
            <% if @event.tickets.empty? && (signed_in? && @event.can_be_modified_by?(current_user)) %>
              <h3>Add your free ticket</h3>
              <div class="alert alert-info">Please click the link below to create your free ticket. A free ticket allows members to register their interest with your event.<br>If you do not want a members to be able to join your event, ignore this</div>
              <%= form_for @new_ticket do |f| %>
                <%= f.hidden_field :ticket_type, :value => "Free" %> 
                <%= f.hidden_field :ticket_cost, :value => "0" %> 
                <%= f.hidden_field :quantity, :value => 10000 %> 
                <%= f.hidden_field :start_sale_datetime, :value => Time.now %> 
                <%= f.hidden_field :end_sale_datetime, :value => @event.start_datetime %>
                <%= f.hidden_field :event_id, :value => @event.id %>
                <%= f.submit "Create a FREE ticket", :class => "btn btn-primary" %> 
              <% end %>
            <% else %>              
              <h3>Attend</h3>
              <p>
                <%= link_to "I'm Going!", new_ticket_allocation_path(@event.tickets.first) , class:"btn btn-primary pull-right" %> 
                This event is free to attend, just press the button to add a reminder and party your little hearts out
              </p>
            <% end %>
          <% end %>
        </div>
        <hr>
        <div class="">
          <% if !@event.associate_clubs.empty? %>
            <hr>
            <h4>Assoicated Clubs</h4>
            <%= render @event.associate_clubs %>
          <% end %>
          <% if signed_in? && @event.can_be_modified_by?(current_user) %>
            <%= render partial: "shared_events/form" %>
          <% end %>
        </div>

      </div>
    </div>

  </div>

  <div class="col-sm-6 col-md-4">

    <%= render partial: "events/featured_event", object: @fevent, as: :event %>

    <div class="row">
      <h2>Events</h2>
      <%= render partial: "events/listall_cb", object: @club_events, as: :events %>
    </div>
  </div>

</div>