clubbiz/config/routes.rb
Clubbiz::Application.routes.draw do
 
  get "admins/dashboard"
  get "admins/pending_club/:id" => "admins#pending_club", as: "admins_pending_club"

  get 'club_admins/eventdisplay' => "club_admins#eventdisplay", as: "clubadmin_eventdisplay"
  get "club_admins/dashboard/:id" => "club_admins#dashboard", as: "dashboard"
  get "club_admins/events/:id" => "club_admins#events", as: "clubadmin_events"
  get "club_admins/settings/:id" => "club_admins#settings", as: "clubadmin_settings"
  
  get "permission_denied" => "pages#permission_denied", as: "permission_denied"
  get "about" => "pages#help", as: "help"
  get "terms" => "pages#terms", as: "terms"
  get "privacy" => "pages#privacy", as: "privacy"
  get "about" => "pages#about", as: "about"
  get "search" => "pages#search", as: "search"

  resources :shared_events, only: [:edit, :create, :update, :destroy]

  resources :event_comments, only: [:edit, :create, :update, :destroy]
  get "event_comments/new/:id" => "event_comments#new", as: "new_event_comment"

  resources :club_comments, only: [:edit, :create, :update, :destroy]
  get "club_comments/new/:id" => "club_comments#new", as: "new_club_comment"

  resources :memberships, only: [:index, :edit, :create, :update, :destroy]
  get "memberships/new/:id" => "memberships#new", as: "new_membership"
  
  resources :tickets

  resources :ticket_allocations, except: [:new]
  get "ticket_allocations/new/:id" => "ticket_allocations#new", as: "new_ticket_allocation"

  resources :events, except: [:new]
  get "events/new/:id" => "events#new", as: "new_event"

  devise_for :users
  get "users/:id" => 'users#show', as: 'user'
  resources :clubs

  root to: "pages#home"
  

end

clubbiz/app/models/user.rb
class User < ActiveRecord::Base
  
	has_many :ticket_allocations, dependent: :destroy
	has_many :tickets, :through => :ticket_allocations, dependent: :destroy

	has_many :memberships, dependent: :destroy
	has_many :clubs, :through => :memberships, dependent: :destroy

	def displayname
		"#{first_name} #{last_name}"
	end

	def is_member?(club)
		club.active_memberships.map(&:user_id).include? self.id
	end

	def is_pending?(club)
		club.pending_memberships.map(&:user_id).include? self.id
	end

	def admin?
		self.role == "admin"
	end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

clubbiz/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:show]

  def show
  end

  def get_user
  	@user = User.find(params[:id])
  end

end

clubbiz/app/helpers/users_helper.rb
module UsersHelper
end

clubbiz/app/views/users/_sidenav_signed_in.html.erb
	<li><%= link_to "Home", root_path %></li>
	<li><%= link_to "Notifications", current_user %></li>
	<li><%= link_to "My Clubs", current_user %></li>
	<li><%= link_to "Search Clubs", search_path %></a></li>
	<li><%= link_to "Register your Club", new_club_path %></li>
	<li><%= link_to "My Settings", user_path(current_user) %></li>
	<li><%= link_to "About Us", about_path %></li>

clubbiz/app/views/users/_signin_modal.html.erb
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header" style="background:#ccc">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Sign In</h4></div>
      <div class="modal-body">
        
        <%= form_for(:user, url: session_path(:user)) do |f| %>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, autofocus: true, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control", placeholder: "Email Address", autocomplete: "off" %>
          </div>
          <div class="form-group">
            <%= f.submit "Sign in", class: "btn btn-success btn-block" %>
            <%= link_to "Forgot your password?", new_password_path(resource_name), class: "btn btn-default btn-block" %>
          </div>
        <% end %>
      </div>          
    </div>
  </div>
</div>

clubbiz/app/views/users/show.html.erb
<h1>User Profile Page</h1>

<p>
	<strong>Name</strong><br>
	<%= @user.displayname %>
</p>
<p>
	<strong>Email</strong><br>
	<%= @user.email %>
</p>

<p>
	<strong>Club Memberships</strong>
	<table class="table table-striped">
		<tr>
			<th>Club Name</th>
			<th>Status</th>
			<th>Joined</th>
		</tr>
		<% if !@user.memberships.empty? %>
			<% @user.memberships.each do |ms| %>
			<tr>
				<td><%= ms.club.club_name %></td>
				<td><%= ms.status %></td>
				<td><%= distance_of_time_in_words(ms.created_at, Time.now, true) + ' ago' %></td>
			</tr>
			<% end %>
		<% else %>
			<tr>
				<td colspan='3'><center>Get a move on and join some clubs</center></td>
			</tr>
		<% end %>
	</table>
</p>

<p>
	<strong>Purcahsed Tickets</strong>
	<table class="table table-striped">
		<tr>
			<th>Event</th>
			<th>Ticket Type</th>
			<th>Qty</th>
			<th>Cost</th>
		</tr>
		<% if !@user.ticket_allocations.empty? %>
			<% @user.ticket_allocations.each do |ta| %>
			<tr>
				<td><%= ta.ticket.event.event_name %></td>
				<td><%= ta.ticket.ticket_type%></td>
				<td><%= ta.ticket.quantity %></td>
				<td><%= ta.ticket.ticket_cost %></td>
			</tr>
			<% end %>
		<% else %>
			<tr>
				<td colspan='4'><center>Time to find an event and purchase a ticket</center></td>
			</tr>
		<% end %>
	</table>
</p>