clubbiz/config/routes.rb
Clubbiz::Application.routes.draw do
 
  get "admins/dashboard"
  get "admins/pending_club/:id" => "admins#pending_club", as: "admins_pending_club"

  get 'club_admins/eventdisplay' => "club_admins#eventdisplay", as: "clubadmin_eventdisplay"
  get "club_admins/dashboard/:id" => "club_admins#dashboard", as: "dashboard"
  get "club_admins/events/:id" => "club_admins#events", as: "clubadmin_events"
  get "club_admins/settings/:id" => "club_admins#settings", as: "clubadmin_settings"
  
  get "permission_denied" => "pages#permission_denied", as: "permission_denied"
  get "about" => "pages#help", as: "help"
  get "terms" => "pages#terms", as: "terms"
  get "privacy" => "pages#privacy", as: "privacy"
  get "about" => "pages#about", as: "about"
  get "search" => "pages#search", as: "search"

  resources :shared_events, only: [:edit, :create, :update, :destroy]

  resources :event_comments, only: [:edit, :create, :update, :destroy]
  get "event_comments/new/:id" => "event_comments#new", as: "new_event_comment"

  resources :club_comments, only: [:edit, :create, :update, :destroy]
  get "club_comments/new/:id" => "club_comments#new", as: "new_club_comment"

  resources :memberships, only: [:index, :edit, :create, :update, :destroy]
  get "memberships/new/:id" => "memberships#new", as: "new_membership"
  
  resources :tickets

  resources :ticket_allocations, except: [:new]
  get "ticket_allocations/new/:id" => "ticket_allocations#new", as: "new_ticket_allocation"

  resources :events, except: [:new]
  get "events/new/:id" => "events#new", as: "new_event"

  devise_for :users
  get "users/:id" => 'users#show', as: 'user'
  resources :clubs

  root to: "pages#home"
  

end

clubbiz/app/models/club.rb
class Club < ActiveRecord::Base
	
	validates :club_name, presence: true
	validates :club_description, presence: true
	validates :rego_number, presence: true
	
	has_many :club_comments, dependent: :destroy
	
	has_many :shared_events, dependent: :destroy
	has_many :events, :through => :shared_events, dependent: :destroy
	
	has_many :memberships, dependent: :destroy
	has_many :users, :through => :memberships

	accepts_nested_attributes_for :memberships

	def self.search(query)
		where("club_name like ?", "%#{query}%")
	end

	def active_memberships
		self.memberships.where(status: "active")
	end

	def self.get_pending
		where(status: "pending")
	end

	def get_next_event
		self.events.first || Event.all.first
	end

	def get_club_news
		self.club_comments.where(comment_type: "news")
	end

	def get_associate_clubs
		SharedEvent.all.where(:event_id => self.shared_events.map(&:event_id)).group(:club_id).order(:updated_at)	
	end

	def get_president
		self.users.first
	end

	def pending_memberships
		self.memberships.where(status: "pending")
	end

	def moderators
		self.memberships.where(:role => ["moderator","president"])
	end

	def is_member?(user)
		self.active_memberships.map(&:user_id).include? user.id
	end

	def can_be_modified_by?(user)
		self.moderators.map(&:user_id).include? user.id
	end

end

clubbiz/app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  
  before_action :admin_redirect, except: :update
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
    @events = @club.events
    @fevent = @club.get_next_event #altered to make work when club has no events error
    @club_comments = @club.club_comments
    @club_comment = ClubComment.new
    @membership = Membership.new
    @club_news = ClubComment.new
  end

  # GET /clubs/new
  def new
    @club = Club.new
    @membership = Membership.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.js {}
        format.json { render action: 'show', status: :created, location: @club }
      else
        format.html { render action: 'new' }
        format.json { render :json => { :error => @club.errors.full_message }, :status => 422 }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:club_name, :club_description, :club_website, :rego_number, :status)
    end

    def admin_redirect
      if signed_in? && current_user.admin?
        redirect_to admins_dashboard_path
      end
    end
end

clubbiz/app/helpers/clubs_helper.rb
module ClubsHelper
end

clubbiz/app/views/clubs/_club.html.erb
<div class="media cb-event-list-element">
  <a class="pull-left" href="#">
    <img class="media-object" src="http://placehold.it/80x80">
  </a>
  <div class="media-body">
    <strong><%= link_to club.club_name, club_path(club) %></strong>
    <div class="dropdown pull-right">
      <a data-toggle="dropdown" href="#" style="color: #000"><b class="caret"></b> </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li><a href="">View</a></li>
        <li><a href="">Tickets</a></li>
      </ul>
    </div>
    <br>
    <small><%= club.created_at %><br><em>MUST ADD LOC TO EVENT DB</em><br><%= club.updated_at %></small>
  </div>
</div>

clubbiz/app/views/clubs/_club_comment.html.erb
<a class="pull-left" href="#">
	<span class="glyphicon glyphicon-chevron-right"></span>
</a>

<div class="media-body cb-comment-list-element">
	<h4 class="media-heading"><%= club_comment.comment_title %></h4>
	<%= club_comment.comment_body %><br>
	<small>Posted by <%= club_comment.user.displayname %>, <%= distance_of_time_in_words_to_now(club_comment.created_at) + " ago" %></small>
</div>
	

clubbiz/app/views/clubs/_club_comment_display.html.erb
<% if !@club.club_comments.where(comment_type: "Comment").empty? %>
	<% @club.club_comments.where(comment_type: "Comment").each do |club_comment| %>
		
		<a class="pull-left" href="#">
			<span class="glyphicon glyphicon-chevron-right"></span>
		</a>

		<div class="media-body cb-comment-list-element">
			<h4 class="media-heading"><%= club_comment.comment_title %></h4>
			<%= club_comment.comment_body %><br>
			<small>Posted by <%= club_comment.user.displayname %>, <%= distance_of_time_in_words_to_now(club_comment.created_at) + " ago" %></small>
		</div>
	<% end %>
<% else %>
	<div><center>There are no comments, must be doing somethin' right</center></div>
<% end %>

clubbiz/app/views/clubs/_club_rego_submit_btn.html.erb
<%= form_for club do |f| %>
	<%= f.hidden_field :status, :value => "pending" %>
	<%= f.submit "Submit" %>
<% end %>

clubbiz/app/views/clubs/_edit_form.html.erb
<div class="col-md-7">
  
  <h4><em>Club Information</em></h4>
  <%= form_for(@club) do |f| %>
    <div class="form-group">
      <%= f.label :club_name %>
      <%= f.text_field :club_name, class: "form-control", placeholder: "Enter email" %>
    </div>
    <div class="form-group">
      <%= f.label :club_description %>
      <%= f.text_field :club_description, class: "form-control", rows: "3", placeholder: "Description" %>
    </div>
    <div class="form-group">
      <%= f.label :club_website %>
      <%= f.text_field :club_website, class: "form-control", placeholder: "Password" %>
    </div>
    <div class="form-group">
      <%= f.label :rego_number %>
      <%= f.text_field :rego_number, class: "form-control", placeholder: "Password" %>
    </div>
    <%= f.hidden_field :status, :value => "prereg" %>
    <%= f.submit "Go", :class => "btn btn-primary" %>
  <% end %>

  <h4><em>Moderator Information</em></h4>
  <div id="cb-moderators-form-cont"> 
    <%= render @club.moderators %>
  </div>
  <h5><em>Add New Moderator</em></h5>
  <%= render "clubs/moderator_form" %>

</div>
<div class="col-md-5">
  <h4>Why ClubBiz?</h4>
  <p>
    Signing up for ClubBiz allows for your club to manage its events and tickets with ease. Take the worry out of promoting your event and informing your members of your latest event, and just get on with it.
  </p>
  <p>
    With all of your current members, and hundreds of potential new members already using our site, you'd be stupid not to continue. Fill in your details and click 'Next'.
  </p>
</div>

clubbiz/app/views/clubs/_listall.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>club_name</th>
      <th>club_description</th>
      <th>club_website</th>
      <th>rego_number</th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= link_to club.club_name, club %></td>
        <td><%= club.club_description %></td>
        <td><%= club.club_website %></td>
        <td><%= club.rego_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

clubbiz/app/views/clubs/_new_club_rego_display.html.erb
<table class="table">
	<tr>
		<td>Club Name</td>
		<td><%= club.club_name %></td>
	</tr>
	<tr>
		<td>Club Description</td>
		<td><%= club.club_description %></td>
	</tr>
	<tr>
		<td>Club Website</td>
		<td><%= club.club_website %></td>
	</tr>
	<tr>
		<td>Rego Number</td>
		<td><%= club.rego_number %></td>
	</tr>
</table>

clubbiz/app/views/clubs/_new_form.html.erb
<div class="row" id="main-content">
  

  <div class="col-md-7">
    <h2 style="margin-top:0">Register your Club</h2>                   
  </div>

  <div class="col-md-12"></div>

  <div class="col-md-7">
          
    <%= form_for(@club) do |f| %>
      <% if @club.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

          <ul>
          <% @club.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="form-group">
        <%= f.label :club_name %>
        <%= f.text_field :club_name, class: "form-control", placeholder: "Enter email" %>
      </div>
      <div class="form-group">
        <%= f.label :club_description %>
        <%= f.text_field :club_description, class: "form-control", rows: "3", placeholder: "Description" %>
      </div>
      <div class="form-group">
        <%= f.label :club_website %>
        <%= f.text_field :club_website, class: "form-control", placeholder: "Password" %>
      </div>
      <div class="form-group">
        <%= f.label :rego_number %>
        <%= f.text_field :rego_number, class: "form-control", placeholder: "Password" %>
      </div>
      <%= f.hidden_field :status, :value => "prereg" %>
      <%= f.submit "Create Club", :class => "btn btn-success pull-right" %>
      
    <% end %>

  </div>
  <div class="col-md-5">
    <h4>Why ClubBiz?</h4>
    <p>
      Signing up for ClubBiz allows for your club to manage its events and tickets with ease. Take the worry out of promoting your event and informing your members of your latest event, and just get on with it.
    </p>
    <p>
      With all of your current members, and hundreds of potential new members already using our site, you'd be stupid not to continue. Fill in your details and click 'Next'.
    </p>
  </div>
</div>

clubbiz/app/views/clubs/_president_form.html.erb
<%= form_for(@membership, remote: true) do |f| %>
	<div class="form-group">
		<%= f.text_field :user_id, class: "form-control", placeholder: "User ID" %>
	</div>
	<div class="form-group">
		<%= f.text_field :role, :value => "president", class: "form-control" %>
	</div>
		<% if @club %>
			<%= f.hidden_field :club_id, :value => @club.id %>
		<%= f.hidden_field :status, :value => "active" %>
		<% else %>
			<%= f.hidden_field :club_id, class: "cb-clubid" %>
		<%= f.hidden_field :status, :value => "pending" %>
		<% end %>
		<%= f.submit "Go", :class => "btn btn-primary" %>
<% end %>

clubbiz/app/views/clubs/_treasurer_form.html.erb
<%= form_for(@membership, remote: true, :url => {:action => "create_treasurer"}) do |f| %>
	<div class="form-group">
		<%= f.text_field :user_id, class: "form-control", placeholder: "User ID" %>
	</div>
	<div class="form-group">
		<%= f.text_field :role, :value => "treasurer", class: "form-control" %>
	</div>
		<% if @club %>
			<%= f.hidden_field :club_id, :value => @club.id %>
		<%= f.hidden_field :status, :value => "active" %>
		<% else %>
			<%= f.hidden_field :club_id, class: "cb-clubid" %>
		<%= f.hidden_field :status, :value => "pending" %>
		<% end %>
		<%= f.submit "Go", :class => "btn btn-primary" %>
<% end %>

clubbiz/app/views/clubs/edit.html.erb
<div class="row" id="main-content">

  <div class="col-md-7">
    <h2 style="margin-top:0">Edit your Club</h2>                   
  </div>

  <div class="col-md-12"></div>
  <%= render "edit_form" %>

</div>

clubbiz/app/views/clubs/index.html.erb
<h1>Listing all clubs</h1>

<%= render "listall" %>

<br>

<% if signed_in? %>	
	<%= link_to 'New Club', new_club_path, class: "btn btn-default" %>
<% end %>

clubbiz/app/views/clubs/new.html.erb
<h1>New club</h1>

<%= render 'new_form' %>

<%= link_to 'Back', clubs_path, class: "btn btn-default" %>

clubbiz/app/views/clubs/show.html.erb
<div class="row" id="main-content">
  <div class="col-md-4 col-md-pull-2 pull-right cb-search-element">
    <%= render "shared/search_all" %>
  </div>



  <div class="col-sm-6 col-md-6">

    <div class="row">
      <div class="col-md-10">
        <div class="row">
          <img src="http://placehold.it/100x100" class = "pull-left" width="65px"><h2><%= @club.club_name %></h2>
          <ul class="nav nav-tabs pull-right">
            <li class="active"><a href="#home" data-toggle="tab">Home</a></li>
            <li><a href="#gallery" data-toggle="tab">Gallery</a></li>
            <li><a href="#discussions" data-toggle="tab">Discussions</a></li>
          </ul>
        </div>  
        <div class="tab-content row">
          <div class="tab-pane fade in active" id="home">
            <div class="col-md-6">
              <p>
                <%= @club.club_description %>
              </p> 
            </div>
            <div class="col-md-6">
              <img src="http://placehold.it/170x170" class = "pull-right">
            </div>
            <div class ="col-md-8">
              <h3>Announcements</h3>             
              
              <%= render @club.get_club_news.limit(3) %>

            </div>
            <% if signed_in? && @club.can_be_modified_by?(current_user) %>
              <%= render partial: "club_comments/news_form", object: {:new_comment => @new_news, :current_user => current_user, :club => @club} %>
            <% end %>
            <% if signed_in? %>
              <% if @club.can_be_modified_by?(current_user) %>
                DO IT
                <div class ="col-md-4 text-right">
                  <h3>Moderator Settings</h3>
                  <p><a href="#" class="btn btn-primary" role="button">Click Here</a></p>
                </div>
              <% end %>
              <% if current_user.is_member?(@club) %>
                <h5>Current Member</h5>
                <%= link_to "My Settings", user_path(current_user), class: "btn btn-default" %>
              <% elsif current_user.is_pending?(@club) %>
                <h5>Your membership request is being processed, you will be notified when you have been acepted</h5>
                <%= link_to "My Settings", user_path(current_user), class: "btn btn-default" %>
              <% else %>
                <%= form_for @membership do |f| %>
                  <%= f.hidden_field :club_id, :value => @club.id %>
                  <%= f.hidden_field :user_id, :value => current_user.id %>
                  <%= f.hidden_field :status, :value => "pending" %>
                  <%= f.hidden_field :role, :value => "member" %>
                  <%= f.submit "Join Club" %>
                <% end %>
              <% end %>
            <% end %>
          </div>

          <div class="tab-pane fade" id="gallery">Images from our club.
            <div class="row">
              <div class="col-xs-6 col-md-4">
                <a href="#" class="">
                 <img src="http://placehold.it/150x150" class = "pull-right"  />
               </a>
             </div>
             <div class="col-xs-6 col-md-4">
              <a href="#" class="">
                <img src="http://placehold.it/150x150" class = "pull-right"/>
              </a>
            </div>
            <div class="col-xs-6 col-md-4">
              <a href="#" class="">
                <img src="http://placehold.it/150x150" class = "pull-right" />
              </a>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-6 col-md-4">
              <a href="#" class="">
               <img src="http://placehold.it/150x150" class = "pull-right"  />
             </a>
           </div>
           <div class="col-xs-6 col-md-4">
            <a href="#" class="">
              <img src="http://placehold.it/150x150" class = "pull-right" />
            </a>
          </div>
          <div class="col-xs-6 col-md-4">
            <a href="#" class="">
              <img src="http://placehold.it/150x150" class = "pull-right" />
            </a>
          </div>
        </div>

      </div>

      <div class="tab-pane fade" id="discussions">
        <div id="cb-event-comment-wrapper">
                    
          <%= render @club_comments %>
          
        </div>
        <% if signed_in? %>
          <%= render partial: "club_comments/form", object: {:new_comment => @new_comment, :current_user => current_user, :club => @club} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-10 ">
    <hr>
    <div class="">
      <h3>Similar Clubs</h3>
      <% @club.get_associate_clubs.limit(3).each do |shared_event| %>
        <%= shared_event.club.club_name %>
        <%= render partial: "clubs/associate_club", collection: shared_event.club, as: :club %>
      <% end %>
            
        
      </div>
    </div>

  </div>



</div>

<div class="col-sm-6 col-md-4">

  <%= render partial: "events/featured_event", object: @fevent, as: :event %>
  <div class="row">
    <h2>Events</h2>
    <% if @club.events.empty? %>
      <div>No Events</div>
    <% else %>
      <%= render partial: "events/listall_cb", object: @club.events.limit(3), as: :events %>
    <% end %>
    <% if signed_in? && @club.can_be_modified_by?(current_user) %>
      <%= link_to "Add New Event", new_event_path(@club), class: "btn btn-default btn-block" %>
    <% end %>
  </div>

</div>

</div>